site_name: MiamiLost

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/miamilost.png
  favicon: assets/logos/miamilost.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
