site_name: MiamiLost

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/miamilost.logo.small.png
  favicon: assets/logos/miamilost.logo.small.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - Home: "index.md"
  - Analysis:
      - Introduction: "pages/analysis/00.introduction.md"
      - References:
          - Publications: "pages/analysis/references/00.publications.md"
          - Datasets: "pages/analysis/references/01.datasets.md"
          - Libraries: "pages/analysis/references/02.libraries.md"
          - Services: "pages/analysis/references/03.services.md"
  - Context:
      - Overview: "pages/analysis/00.overview.md"
      # - Authors:
      # - Acknowledgements:
      # - New Worlds 2022: "pages/info/01.new-worlds-2022.md"
  - Resources:
      - Pages: "pages/info/02.page-directory.md"
      - Files: "pages/resources/00.files.md"
      - Datasets: "pages/resources/01.datasets.md"
      # - Issues (github discussions/issues)
      - Repositories:
      # "pages/resources/02.documentation.md"
      # - Repositories:
  - Contact:
      - Contact Methods: "pages/contact/contact-methods.md"
