site_name: MiamiLost

theme:
  name: material
  custom_dir: overrides
  logo: assets/logos/miamilost.png
  favicon: assets/logos/miamilost.png
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite

nav:
  - Home: "index.md"
  - About:
      - Overview: "pages/about/00.overview.md"
      - Authors: "pages/about/01.authors.md"
      - New Worlds: "pages/about/02.new-worlds.md"
      - Acknowledgements: "pages/about/03.acknowledgements.md"
      - Contact: "pages/about/04.contact.md"
  - Analysis:
      - Introduction: "pages/analysis/00.introduction.md"
  # - Documentation:
  - References:
      - Publications: "pages/references/00.publications.md"
      - Datasets: "pages/references/01.datasets.md"
      - Libraries: "pages/references/02.libraries.md"
      - Services: "pages/references/03.services.md"
  - Resources:
      - Repositories: "pages/resources/00.repositories.md"
      - Files: "pages/resources/01.files.md"
      - Datasets: "pages/resources/02.datasets.md"
      - Discussions: "pages/resources/03.discussions.md"
      - Tools: "pages/resources/04.tools.md"
  - Pages: "pages.md"
